#ifndef REG_IDS_H
#define REG_IDS_H


// THIS FILE IS GENERATED AUTOMATICALLY!
// DO NOT EDIT THIS FILE!

// Modules for registers

// Begin

// Conf
// Nominal values


// NTC
#define REG_ID_NTC_NTC_0    200
#define REG_ID_NTC_NTC_1    201
#define REG_ID_NTC_NTC_2    202
#define REG_ID_NTC_NTC_3    203
#define REG_ID_NTC_NTC_4    204
#define REG_ID_NTC_NTC_5    205


// End

#endif /* REG_IDS_H */
