#ifndef REG_IDS_H
#define REG_IDS_H


// THIS FILE IS GENERATED AUTOMATICALLY!
// DO NOT EDIT THIS FILE!


// user code begin

// user code end

#define REG_ID_DEVICE_TYPE_VALUE 0x100000 /*  */
#define REG_ID_ERROR_REGISTER_VALUE 0x100100 /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_NUMBER_OF_ERRORS 0x100300 /* Number of sub-entries */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_0 0x100301 /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_1 0x100302 /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_2 0x100303 /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_3 0x100304 /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_4 0x100305 /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_5 0x100306 /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_6 0x100307 /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_7 0x100308 /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_8 0x100309 /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_9 0x10030a /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_10 0x10030b /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_11 0x10030c /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_12 0x10030d /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_13 0x10030e /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_14 0x10030f /*  */
#define REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_15 0x100310 /*  */
#define REG_ID_COB_ID_SYNC_MESSAGE_VALUE 0x100500 /*  */
#define REG_ID_COMMUNICATION_CYCLE_PERIOD_VALUE 0x100600 /*  */
#define REG_ID_SYNCHRONOUS_WINDOW_LENGTH_VALUE 0x100700 /*  */
#define REG_ID_STORE_PARAMETERS_HIGHEST_SUB_INDEX_SUPPORTED 0x101000 /* Number of sub-entries */
#define REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_0 0x101001 /*  */
#define REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_1 0x101002 /*  */
#define REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_2 0x101003 /*  */
#define REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_3 0x101004 /*  */
#define REG_ID_RESTORE_DEFAULT_PARAMETERS_HIGHEST_SUB_INDEX_SUPPORTED 0x101100 /* Number of sub-entries */
#define REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_0 0x101101 /*  */
#define REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_1 0x101102 /*  */
#define REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_2 0x101103 /*  */
#define REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_3 0x101104 /*  */
#define REG_ID_COB_ID_TIME_STAMP_OBJECT_VALUE 0x101200 /*  */
#define REG_ID_COB_ID_EMCY_VALUE 0x101400 /*  */
#define REG_ID_INHIBIT_TIME_EMCY_VALUE 0x101500 /*  */
#define REG_ID_CONSUMER_HEARTBEAT_TIME_HIGHEST_SUB_INDEX_SUPPORTED 0x101600 /* Number of sub-entries */
#define REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_0 0x101601 /*  */
#define REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_1 0x101602 /*  */
#define REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_2 0x101603 /*  */
#define REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_3 0x101604 /*  */
#define REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_4 0x101605 /*  */
#define REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_5 0x101606 /*  */
#define REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_6 0x101607 /*  */
#define REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_7 0x101608 /*  */
#define REG_ID_PRODUCER_HEARTBEAT_TIME_VALUE 0x101700 /*  */
#define REG_ID_IDENTITY_HIGHEST_SUB_INDEX_SUPPORTED 0x101800 /* Number of sub-entries */
#define REG_ID_IDENTITY_VENDOR_ID 0x101801 /*  */
#define REG_ID_IDENTITY_PRODUCT_CODE 0x101802 /*  */
#define REG_ID_IDENTITY_REVISION_NUMBER 0x101803 /*  */
#define REG_ID_IDENTITY_SERIAL_NUMBER 0x101804 /*  */
#define REG_ID_SYNCHRONOUS_COUNTER_OVERFLOW_VALUE_VALUE 0x101900 /*  */
#define REG_ID_SDO_SERVER_PARAMETER_HIGHEST_SUB_INDEX_SUPPORTED 0x120000 /* Number of sub-entries */
#define REG_ID_SDO_SERVER_PARAMETER_COB_ID_CLIENT_TO_SERVER__RX_ 0x120001 /*  */
#define REG_ID_SDO_SERVER_PARAMETER_COB_ID_SERVER_TO_CLIENT__TX_ 0x120002 /*  */
#define REG_ID_SDO_CLIENT_PARAMETER_COUNT 0x128000 /* Number of sub-entries */
#define REG_ID_SDO_CLIENT_PARAMETER_COB_ID_CLIENT_TO_SERVER__TX_ 0x128001 /*  */
#define REG_ID_SDO_CLIENT_PARAMETER_COB_ID_SERVER_TO_CLIENT__RX_ 0x128002 /*  */
#define REG_ID_SDO_CLIENT_PARAMETER_NODE_ID_OF_THE_SDO_SERVER 0x128003 /*  */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_HIGHEST_SUB_INDEX_SUPPORTED 0x140000 /* Number of sub-entries */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_COB_ID_USED_BY_RPDO 0x140001 /*  */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_TRANSMISSION_TYPE 0x140002 /*  */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_EVENT_TIMER 0x140005 /*  */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_HIGHEST_SUB_INDEX_SUPPORTED 0x140100 /* Number of sub-entries */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_COB_ID_USED_BY_RPDO 0x140101 /*  */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_TRANSMISSION_TYPE 0x140102 /*  */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_EVENT_TIMER 0x140105 /*  */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_HIGHEST_SUB_INDEX_SUPPORTED 0x140200 /* Number of sub-entries */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_COB_ID_USED_BY_RPDO 0x140201 /*  */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_TRANSMISSION_TYPE 0x140202 /*  */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_EVENT_TIMER 0x140205 /*  */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_HIGHEST_SUB_INDEX_SUPPORTED 0x140300 /* Number of sub-entries */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_COB_ID_USED_BY_RPDO 0x140301 /*  */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_TRANSMISSION_TYPE 0x140302 /*  */
#define REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_EVENT_TIMER 0x140305 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO 0x160000 /* Number of sub-entries */
#define REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_1 0x160001 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_2 0x160002 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_3 0x160003 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_4 0x160004 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_5 0x160005 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_6 0x160006 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_7 0x160007 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_8 0x160008 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1601_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO 0x160100 /* Number of sub-entries */
#define REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_1 0x160101 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_2 0x160102 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_3 0x160103 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_4 0x160104 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_5 0x160105 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_6 0x160106 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_7 0x160107 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_8 0x160108 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1602_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO 0x160200 /* Number of sub-entries */
#define REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_1 0x160201 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_2 0x160202 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_3 0x160203 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_4 0x160204 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_5 0x160205 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_6 0x160206 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_7 0x160207 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_8 0x160208 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1603_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO 0x160300 /* Number of sub-entries */
#define REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_1 0x160301 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_2 0x160302 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_3 0x160303 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_4 0x160304 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_5 0x160305 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_6 0x160306 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_7 0x160307 /*  */
#define REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_8 0x160308 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_HIGHEST_SUB_INDEX_SUPPORTED 0x180000 /* Number of sub-entries */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_COB_ID_USED_BY_TPDO 0x180001 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_TRANSMISSION_TYPE 0x180002 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_INHIBIT_TIME 0x180003 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_EVENT_TIMER 0x180005 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_SYNC_START_VALUE 0x180006 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_HIGHEST_SUB_INDEX_SUPPORTED 0x180100 /* Number of sub-entries */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_COB_ID_USED_BY_TPDO 0x180101 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_TRANSMISSION_TYPE 0x180102 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_INHIBIT_TIME 0x180103 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_EVENT_TIMER 0x180105 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_SYNC_START_VALUE 0x180106 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_HIGHEST_SUB_INDEX_SUPPORTED 0x180200 /* Number of sub-entries */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_COB_ID_USED_BY_TPDO 0x180201 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_TRANSMISSION_TYPE 0x180202 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_INHIBIT_TIME 0x180203 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_EVENT_TIMER 0x180205 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_SYNC_START_VALUE 0x180206 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_HIGHEST_SUB_INDEX_SUPPORTED 0x180300 /* Number of sub-entries */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_COB_ID_USED_BY_TPDO 0x180301 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_TRANSMISSION_TYPE 0x180302 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_INHIBIT_TIME 0x180303 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_EVENT_TIMER 0x180305 /*  */
#define REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_SYNC_START_VALUE 0x180306 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO 0x1a0000 /* Number of sub-entries */
#define REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_1 0x1a0001 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_2 0x1a0002 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_3 0x1a0003 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_4 0x1a0004 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_5 0x1a0005 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_6 0x1a0006 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_7 0x1a0007 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_8 0x1a0008 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A01_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO 0x1a0100 /* Number of sub-entries */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_1 0x1a0101 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_2 0x1a0102 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_3 0x1a0103 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_4 0x1a0104 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_5 0x1a0105 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_6 0x1a0106 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_7 0x1a0107 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_8 0x1a0108 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A02_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO 0x1a0200 /* Number of sub-entries */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_1 0x1a0201 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_2 0x1a0202 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_3 0x1a0203 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_4 0x1a0204 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_5 0x1a0205 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_6 0x1a0206 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_7 0x1a0207 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_8 0x1a0208 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A03_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO 0x1a0300 /* Number of sub-entries */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_1 0x1a0301 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_2 0x1a0302 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_3 0x1a0303 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_4 0x1a0304 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_5 0x1a0305 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_6 0x1a0306 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_7 0x1a0307 /*  */
#define REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_8 0x1a0308 /*  */
#define REG_ID_CONF_COUNT 0x200000 /* Number of sub entries count */
#define REG_ID_CONF_CONTROL 0x200001 /* Слово управления. */
#define REG_ID_CONF_STATUS 0x200002 /* Слово состояния. */
#define REG_ID_SYS_COUNT 0x201000 /* Number of sub entries count */
#define REG_ID_SYS_CONTROL 0x201001 /* Слово управления. */
#define REG_ID_SYS_STATUS 0x201002 /* Слово состояния. */
#define REG_ID_SYS_ERRORS 0x201003 /* Ошибки. */
#define REG_ID_SYS_WARNINGS 0x201004 /* Предупреждения. */
#define REG_ID_SYS_STATE 0x201005 /* Состояние. */
#define REG_ID_SYS_TIM_COUNT 0x202000 /* Number of sub entries count */
#define REG_ID_SYS_TIM_CONTROL 0x202001 /* Слово управления. */
#define REG_ID_SYS_TIM_STATUS 0x202002 /* Слово состояния. */
#define REG_ID_SYS_TIM_OUT_COUNTER 0x202003 /* Счётчик тиков. */
#define REG_ID_MS_TIM_COUNT 0x203000 /* Number of sub entries count */
#define REG_ID_MS_TIM_CONTROL 0x203001 /* Слово управления. */
#define REG_ID_MS_TIM_STATUS 0x203002 /* Слово состояния. */
#define REG_ID_MS_TIM_OUT_COUNTER 0x203003 /* Счётчик тиков. */
#define REG_ID_CLI_COUNT 0x204000 /* Number of sub entries count */
#define REG_ID_CLI_CONTROL 0x204001 /* Слово управления. */
#define REG_ID_CLI_STATUS 0x204002 /* Слово состояния. */
#define REG_ID_RGB_LED_COUNT 0x205000 /* Number of sub entries count */
#define REG_ID_RGB_LED_CONTROL 0x205001 /* Слово управления. */
#define REG_ID_RGB_LED_STATUS 0x205002 /* Слово состояния. */
#define REG_ID_RGB_LED_IN_DATA 0x205003 /*  */
#define REG_ID_MSDI_COUNT 0x206000 /* Number of sub entries count */
#define REG_ID_MSDI_CONTROL 0x206001 /* Слово управления. */
#define REG_ID_MSDI_STATUS 0x206002 /* Слово состояния. */
#define REG_ID_MSDI_OUT_DIGITAL 0x206003 /*  */
#define REG_ID_MSDI_OUT_ANALOG0 0x206004 /*  */
#define REG_ID_MSDI_OUT_ANALOG1 0x206005 /*  */
#define REG_ID_MSDI_OUT_ANALOG2 0x206006 /*  */
#define REG_ID_MSDI_OUT_ANALOG3 0x206007 /*  */
#define REG_ID_MSDI_OUT_ANALOG4 0x206008 /*  */
#define REG_ID_MSDI_OUT_ANALOG5 0x206009 /*  */
#define REG_ID_MSDI_OUT_ANALOG6 0x20600a /*  */
#define REG_ID_MSDI_OUT_ANALOG7 0x20600b /*  */
#define REG_ID_MSDI_OUT_REF 0x20600c /*  */
#define REG_ID_MSDI_OUT_VCC 0x20600d /*  */
#define REG_ID_NTC_TEMP_COUNT 0x207000 /* Number of sub entries count */
#define REG_ID_NTC_TEMP_CONTROL 0x207001 /* Слово управления. */
#define REG_ID_NTC_TEMP_STATUS 0x207002 /* Слово состояния. */
#define REG_ID_NTC_TEMP_OUT_TEMP0 0x207003 /*  */
#define REG_ID_NTC_TEMP_OUT_TEMP1 0x207004 /*  */
#define REG_ID_NTC_TEMP_OUT_TEMP2 0x207005 /*  */
#define REG_ID_NTC_TEMP_OUT_TEMP3 0x207006 /*  */
#define REG_ID_NTC_TEMP_OUT_TEMP4 0x207007 /*  */
#define REG_ID_NTC_TEMP_OUT_TEMP5 0x207008 /*  */
#define REG_ID_NTC_TEMP_OUT_OHM0 0x207009 /*  */
#define REG_ID_NTC_TEMP_OUT_OHM1 0x20700a /*  */
#define REG_ID_NTC_TEMP_OUT_OHM2 0x20700b /*  */
#define REG_ID_NTC_TEMP_OUT_OHM3 0x20700c /*  */
#define REG_ID_NTC_TEMP_OUT_OHM4 0x20700d /*  */
#define REG_ID_NTC_TEMP_OUT_OHM5 0x20700e /*  */
#define REG_ID_DO_RELAY_COUNT 0x208000 /* Number of sub entries count */
#define REG_ID_DO_RELAY_CONTROL 0x208001 /* Слово управления. */
#define REG_ID_DO_RELAY_STATUS 0x208002 /* Слово состояния. */
#define REG_ID_DO_RELAY_IN_DATA 0x208003 /*  */
#define REG_ID_DO_NCV7608_COUNT 0x209000 /* Number of sub entries count */
#define REG_ID_DO_NCV7608_CONTROL 0x209001 /* Слово управления. */
#define REG_ID_DO_NCV7608_STATUS 0x209002 /* Слово состояния. */
#define REG_ID_DO_NCV7608_IN_DATA 0x209003 /*  */
#define REG_ID_DIGITAL_IN_COUNT 0x20a000 /* Number of sub entries count */
#define REG_ID_DIGITAL_IN_CONTROL 0x20a001 /* Слово управления. */
#define REG_ID_DIGITAL_IN_STATUS 0x20a002 /* Слово состояния. */
#define REG_ID_DIGITAL_IN_OUT_DATA 0x20a003 /* Выход дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT0 0x20a004 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT1 0x20a005 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT2 0x20a006 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT3 0x20a007 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT4 0x20a008 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT5 0x20a009 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT6 0x20a00a /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT7 0x20a00b /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT8 0x20a00c /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT9 0x20a00d /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT10 0x20a00e /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT11 0x20a00f /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT12 0x20a010 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT13 0x20a011 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT14 0x20a012 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT15 0x20a013 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT16 0x20a014 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT17 0x20a015 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT18 0x20a016 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT19 0x20a017 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT20 0x20a018 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT21 0x20a019 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT22 0x20a01a /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT23 0x20a01b /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT24 0x20a01c /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT25 0x20a01d /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT26 0x20a01e /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT27 0x20a01f /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT28 0x20a020 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT29 0x20a021 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT30 0x20a022 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_INVERT31 0x20a023 /* Параметр инверсии дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT0 0x20a024 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT1 0x20a025 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT2 0x20a026 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT3 0x20a027 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT4 0x20a028 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT5 0x20a029 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT6 0x20a02a /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT7 0x20a02b /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT8 0x20a02c /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT9 0x20a02d /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT10 0x20a02e /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT11 0x20a02f /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT12 0x20a030 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT13 0x20a031 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT14 0x20a032 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT15 0x20a033 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT16 0x20a034 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT17 0x20a035 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT18 0x20a036 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT19 0x20a037 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT20 0x20a038 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT21 0x20a039 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT22 0x20a03a /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT23 0x20a03b /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT24 0x20a03c /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT25 0x20a03d /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT26 0x20a03e /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT27 0x20a03f /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT28 0x20a040 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT29 0x20a041 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT30 0x20a042 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_SELECT31 0x20a043 /* Параметр выбора дискретных входов */
#define REG_ID_DIGITAL_IN_T_SET0 0x20a044 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET1 0x20a045 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET2 0x20a046 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET3 0x20a047 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET4 0x20a048 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET5 0x20a049 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET6 0x20a04a /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET7 0x20a04b /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET8 0x20a04c /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET9 0x20a04d /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET10 0x20a04e /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET11 0x20a04f /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET12 0x20a050 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET13 0x20a051 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET14 0x20a052 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET15 0x20a053 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET16 0x20a054 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET17 0x20a055 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET18 0x20a056 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET19 0x20a057 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET20 0x20a058 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET21 0x20a059 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET22 0x20a05a /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET23 0x20a05b /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET24 0x20a05c /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET25 0x20a05d /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET26 0x20a05e /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET27 0x20a05f /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET28 0x20a060 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET29 0x20a061 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET30 0x20a062 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_SET31 0x20a063 /* Параметр задержки установки */
#define REG_ID_DIGITAL_IN_T_RESET0 0x20a064 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET1 0x20a065 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET2 0x20a066 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET3 0x20a067 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET4 0x20a068 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET5 0x20a069 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET6 0x20a06a /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET7 0x20a06b /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET8 0x20a06c /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET9 0x20a06d /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET10 0x20a06e /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET11 0x20a06f /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET12 0x20a070 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET13 0x20a071 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET14 0x20a072 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET15 0x20a073 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET16 0x20a074 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET17 0x20a075 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET18 0x20a076 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET19 0x20a077 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET20 0x20a078 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET21 0x20a079 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET22 0x20a07a /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET23 0x20a07b /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET24 0x20a07c /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET25 0x20a07d /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET26 0x20a07e /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET27 0x20a07f /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET28 0x20a080 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET29 0x20a081 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET30 0x20a082 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_IN_T_RESET31 0x20a083 /* Параметр задержки сброса */
#define REG_ID_DIGITAL_OUT_COUNT 0x20b000 /* Number of sub entries count */
#define REG_ID_DIGITAL_OUT_CONTROL 0x20b001 /* Слово управления. */
#define REG_ID_DIGITAL_OUT_STATUS 0x20b002 /* Слово состояния. */
#define REG_ID_DIGITAL_OUT_IN_DATA 0x20b003 /*  */
#define REG_ID_DIGITAL_OUT_INVERT 0x20b004 /*  */
#define REG_ID_DIGITAL_OUT_SELECT0 0x20b005 /*  */
#define REG_ID_DIGITAL_OUT_SELECT1 0x20b006 /*  */
#define REG_ID_DIGITAL_OUT_SELECT2 0x20b007 /*  */
#define REG_ID_DIGITAL_OUT_SELECT3 0x20b008 /*  */
#define REG_ID_DIGITAL_OUT_SELECT4 0x20b009 /*  */
#define REG_ID_DIGITAL_OUT_SELECT5 0x20b00a /*  */
#define REG_ID_DIGITAL_OUT_SELECT6 0x20b00b /*  */
#define REG_ID_DIGITAL_OUT_SELECT7 0x20b00c /*  */
#define REG_ID_DIGITAL_OUT_SELECT8 0x20b00d /*  */
#define REG_ID_DIGITAL_OUT_SELECT9 0x20b00e /*  */
#define REG_ID_DIGITAL_OUT_SELECT10 0x20b00f /*  */
#define REG_ID_DIGITAL_OUT_SELECT11 0x20b010 /*  */
#define REG_ID_DIGITAL_OUT_SELECT12 0x20b011 /*  */
#define REG_ID_DIGITAL_OUT_SELECT13 0x20b012 /*  */
#define REG_ID_DIGITAL_OUT_SELECT14 0x20b013 /*  */
#define REG_ID_DIGITAL_OUT_SELECT15 0x20b014 /*  */
#define REG_ID_DIGITAL_OUT_SELECT16 0x20b015 /*  */
#define REG_ID_DIGITAL_OUT_SELECT17 0x20b016 /*  */
#define REG_ID_DIGITAL_OUT_SELECT18 0x20b017 /*  */
#define REG_ID_DIGITAL_OUT_SELECT19 0x20b018 /*  */
#define REG_ID_DIGITAL_OUT_SELECT20 0x20b019 /*  */
#define REG_ID_DIGITAL_OUT_SELECT21 0x20b01a /*  */
#define REG_ID_DIGITAL_OUT_SELECT22 0x20b01b /*  */
#define REG_ID_DIGITAL_OUT_SELECT23 0x20b01c /*  */
#define REG_ID_DIGITAL_OUT_SELECT24 0x20b01d /*  */
#define REG_ID_DIGITAL_OUT_SELECT25 0x20b01e /*  */
#define REG_ID_DIGITAL_OUT_SELECT26 0x20b01f /*  */
#define REG_ID_DIGITAL_OUT_SELECT27 0x20b020 /*  */
#define REG_ID_DIGITAL_OUT_SELECT28 0x20b021 /*  */
#define REG_ID_DIGITAL_OUT_SELECT29 0x20b022 /*  */
#define REG_ID_DIGITAL_OUT_SELECT30 0x20b023 /*  */
#define REG_ID_DIGITAL_OUT_SELECT31 0x20b024 /*  */
#define REG_ID_MSO_COUNT 0x20c000 /* Number of sub entries count */
#define REG_ID_MSO_CONTROL 0x20c001 /* Слово управления. */
#define REG_ID_MSO_STATUS 0x20c002 /* Слово состояния. */
#define REG_ID_MSO_CHANNEL0 0x20c003 /*  */
#define REG_ID_MSO_CHANNEL1 0x20c004 /*  */
#define REG_ID_MSO_CHANNEL2 0x20c005 /*  */
#define REG_ID_MSO_CHANNEL3 0x20c006 /*  */
#define REG_ID_MSO_CHANNEL4 0x20c007 /*  */
#define REG_ID_MSO_CHANNEL5 0x20c008 /*  */
#define REG_ID_MSO_CHANNEL6 0x20c009 /*  */
#define REG_ID_MSO_CHANNEL7 0x20c00a /*  */
#define REG_ID_MSO_CHANNEL8 0x20c00b /*  */
#define REG_ID_MSO_CHANNEL9 0x20c00c /*  */
#define REG_ID_MSO_CHANNEL10 0x20c00d /*  */
#define REG_ID_MSO_CHANNEL11 0x20c00e /*  */
#define REG_ID_MSO_CHANNEL12 0x20c00f /*  */
#define REG_ID_MSO_CHANNEL13 0x20c010 /*  */
#define REG_ID_MSO_CHANNEL14 0x20c011 /*  */
#define REG_ID_MSO_CHANNEL15 0x20c012 /*  */
#define REG_ID_MSO_CHANNEL16 0x20c013 /*  */
#define REG_ID_MSO_CHANNEL17 0x20c014 /*  */
#define REG_ID_MSO_CHANNEL18 0x20c015 /*  */
#define REG_ID_MSO_CHANNEL19 0x20c016 /*  */
#define REG_ID_MSO_CHANNEL20 0x20c017 /*  */
#define REG_ID_MSO_CHANNEL21 0x20c018 /*  */
#define REG_ID_MSO_CHANNEL22 0x20c019 /*  */
#define REG_ID_MSO_CHANNEL23 0x20c01a /*  */
#define REG_ID_MSO_CHANNEL24 0x20c01b /*  */
#define REG_ID_MSO_CHANNEL25 0x20c01c /*  */
#define REG_ID_MSO_CHANNEL26 0x20c01d /*  */
#define REG_ID_MSO_CHANNEL27 0x20c01e /*  */
#define REG_ID_MSO_CHANNEL28 0x20c01f /*  */
#define REG_ID_MSO_CHANNEL29 0x20c020 /*  */
#define REG_ID_MSO_CHANNEL30 0x20c021 /*  */
#define REG_ID_MSO_CHANNEL31 0x20c022 /*  */
#define REG_ID_AO_DAC7562_COUNT 0x20d000 /* Number of sub entries count */
#define REG_ID_AO_DAC7562_CONTROL 0x20d001 /* Слово управления. */
#define REG_ID_AO_DAC7562_STATUS 0x20d002 /* Слово состояния. */
#define REG_ID_AO_DAC7562_IN_CH_A 0x20d003 /*  */
#define REG_ID_AO_DAC7562_IN_CH_B 0x20d004 /*  */
#define REG_ID_PANEL_LED_COUNT 0x20e000 /* Number of sub entries count */
#define REG_ID_PANEL_LED_CONTROL 0x20e001 /* Слово управления. */
#define REG_ID_PANEL_LED_STATUS 0x20e002 /* Слово состояния. */
#define REG_ID_PANEL_LED_OUT_DATA 0x20e003 /*  */
#define REG_ID_MODBUS_REG_CAN_COUNT 0x20f000 /* Number of sub entries count */
#define REG_ID_MODBUS_REG_CAN_CONTROL 0x20f001 /* Слово управления. */
#define REG_ID_MODBUS_REG_CAN_STATUS 0x20f002 /* Слово состояния. */
#define REG_ID_MODBUS_REG_CAN_REG_ID 0x20f003 /*  */
#define REG_ID_MODBUS_REG_CAN_REG_SIZE 0x20f004 /*  */
#define REG_ID_MODBUS_REG_CAN_REG_DATA 0x20f005 /*  */
#define REG_ID_SETTINGS_COUNT 0x210000 /* Number of sub entries count */
#define REG_ID_SETTINGS_CONTROL 0x210001 /* Слово управления. */
#define REG_ID_SETTINGS_STATUS 0x210002 /* Слово состояния. */
#define REG_ID_CAN_TIM_COUNT 0x211000 /* Number of sub entries count */
#define REG_ID_CAN_TIM_CONTROL 0x211001 /* Слово управления. */
#define REG_ID_CAN_TIM_STATUS 0x211002 /* Слово состояния. */
#define REG_ID_CAN_TIM_OUT_COUNTER 0x211003 /* Счётчик тиков. */

#endif /* REG_IDS_H */
