#ifndef REG_LIST_DATA_H
#define REG_LIST_DATA_H


// THIS FILE IS GENERATED AUTOMATICALLY!
// DO NOT EDIT THIS FILE!

// Modules for registers
#include "modules/modules.h"

// Begin
REGS_BEGIN(REG_ARRAY_NAME)

// Conf
// Nominal values


// NTC
REG(REG_ID_NTC_NTC_0, ntc_temp.out_temp[0], REG_TYPE_I32, REG_FLAG_NONE, REG_ID_NONE)
REG(REG_ID_NTC_NTC_1, ntc_temp.out_temp[1], REG_TYPE_I32, REG_FLAG_NONE, REG_ID_NONE)
REG(REG_ID_NTC_NTC_2, ntc_temp.out_temp[2], REG_TYPE_I32, REG_FLAG_NONE, REG_ID_NONE)
REG(REG_ID_NTC_NTC_3, ntc_temp.out_temp[3], REG_TYPE_I32, REG_FLAG_NONE, REG_ID_NONE)
REG(REG_ID_NTC_NTC_4, ntc_temp.out_temp[4], REG_TYPE_I32, REG_FLAG_NONE, REG_ID_NONE)
REG(REG_ID_NTC_NTC_5, ntc_temp.out_temp[5], REG_TYPE_I32, REG_FLAG_NONE, REG_ID_NONE)


// End
REGS_END()

#endif /* REG_LIST_DATA_H */
