/*
 * gpio_fmc_init.c
 *
 *  Created on: 20 июл. 2024 г.
 *      Author: ruslan
 */

#include "gpio_init.h"

#define FMC_GPIO_COUNT 42
#define FMC_GPIO_NAND_NWP_COUNT 1

const gpio_pin_t GPIO_SRAM_nCE = GPIO_PIN(GPIOD, GPIO_PIN_7);	/*151, PD7,		FMC_NE1,		OFF,		SRAM_nCE_App*/
const gpio_pin_t GPIO_NAND_nCE = GPIO_PIN(GPIOG, GPIO_PIN_9);	/*152, PG9,		FMC_NCE3,		OFF,		NAND_nCE_App*/

const gpio_pin_t GPI_NAND_RnB = GPIO_PIN(GPIOD, GPIO_PIN_6);	/*150, PD6,		FMC_NWAIT,		OFF,		NAND_R\nB_App*/
const gpio_pin_t GPO_NAND_nWP = GPIO_PIN(GPIOF, GPIO_PIN_11);	/*59, PF11,		GPIO_Output,	ON,			NAND_nWP_App*/

const gpio_pin_cfg_t gpio_fmc_cfg[FMC_GPIO_COUNT] = {
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_7, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_ON),		/*151, PD7,		FMC_NE1,		OFF,		SRAM_nCE_App*/
		GPIO_PIN_CFG(GPIOG, GPIO_PIN_9, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_ON),		/*152, PG9,		FMC_NCE3,		OFF,		NAND_nCE_App*/
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_4, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_ON),		/*146, PD4,		FMC_NOE,		OFF,		SRAM_NAND_nOE_App*/
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_5, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_ON),		/*147, PD5,		FMC_NWE,		OFF,		SRAM_NAND_nWE_App*/
		GPIO_PIN_CFG(GPIOE, GPIO_PIN_0, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_ON),		/*169, PE0,		FMC_NBL0,		OFF,		SRAM_nBLE_App*/
		GPIO_PIN_CFG(GPIOE, GPIO_PIN_1, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_ON),		/*170, PE1,		FMC_NBL1,		OFF,		SRAM_nBHE_App*/
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_6, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*150, PD6,		FMC_NWAIT,		OFF,		NAND_R\nB_App*/
		GPIO_PIN_CFG(GPIOF, GPIO_PIN_0, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*16, PF0,		FMC_A0,			OFF,		SRAM_A0_App*/
		GPIO_PIN_CFG(GPIOF, GPIO_PIN_1, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*17, PF1,		FMC_A1,			OFF,		SRAM_A1_App*/
		GPIO_PIN_CFG(GPIOF, GPIO_PIN_2, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*18, PF2,		FMC_A2,			OFF,		SRAM_A2_App*/
		GPIO_PIN_CFG(GPIOF, GPIO_PIN_3, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*19, PF3,		FMC_A3,			OFF,		SRAM_A3_App*/
		GPIO_PIN_CFG(GPIOF, GPIO_PIN_4, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*20, PF4,		FMC_A4,			OFF,		SRAM_A4_App*/
		GPIO_PIN_CFG(GPIOF, GPIO_PIN_5, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*21, PF5,		FMC_A5,			OFF,		SRAM_A5_App*/
		GPIO_PIN_CFG(GPIOF, GPIO_PIN_12, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*60, PF12,		FMC_A6,			OFF,		SRAM_A6_App*/
		GPIO_PIN_CFG(GPIOF, GPIO_PIN_13, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*63, PF13,		FMC_A7,			OFF,		SRAM_A7_App*/
		GPIO_PIN_CFG(GPIOF, GPIO_PIN_14, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*64, PF14,		FMC_A8,			OFF,		SRAM_A8_App*/
		GPIO_PIN_CFG(GPIOF, GPIO_PIN_15, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*65, PF15,		FMC_A9,			OFF,		SRAM_A9_App*/
		GPIO_PIN_CFG(GPIOG, GPIO_PIN_0, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*66, PG0,		FMC_A10,		OFF,		SRAM_A10_App*/
		GPIO_PIN_CFG(GPIOG, GPIO_PIN_1, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*67, PG1,		FMC_A11,		OFF,		SRAM_A11_App*/
		GPIO_PIN_CFG(GPIOG, GPIO_PIN_2, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*106, PG2,		FMC_A12,		OFF,		SRAM_A12_App*/
		GPIO_PIN_CFG(GPIOG, GPIO_PIN_3, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*107, PG3,		FMC_A13,		OFF,		SRAM_A13_App*/
		GPIO_PIN_CFG(GPIOG, GPIO_PIN_4, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*108, PG4,		FMC_A14,		OFF,		SRAM_A14_App*/
		GPIO_PIN_CFG(GPIOG, GPIO_PIN_5, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*109, PG5,		FMC_A15,		OFF,		SRAM_A15_App*/
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_11, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*99, PD11,		FMC_A16 FMC_CLE,OFF,		SRAM_NAND_A16_App*/
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_12, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*100, PD12,	FMC_A17 FMC_ALE,OFF,		SRAM_NAND_A17_App*/
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_13, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*101, PD13,	FMC_A18,		OFF,		SRAM_A18_App*/
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_14, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*104, PD14,	FMC_D0,			OFF,		SRAM_NAND_IO0_App*/
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_15, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*105, PD15,	FMC_D1,			OFF,		SRAM_NAND_IO1_App*/
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_0, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*142, PD0,		FMC_D2,			OFF,		SRAM_NAND_IO2_App*/
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_1, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*143, PD1,		FMC_D3,			OFF,		SRAM_NAND_IO3_App*/
		GPIO_PIN_CFG(GPIOE, GPIO_PIN_7, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*68, PE7,		FMC_D4,			OFF,		SRAM_NAND_IO4_App*/
		GPIO_PIN_CFG(GPIOE, GPIO_PIN_8, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*69, PE8,		FMC_D5,			OFF,		SRAM_NAND_IO5_App*/
		GPIO_PIN_CFG(GPIOE, GPIO_PIN_9, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*70, PE9,		FMC_D6,			OFF,		SRAM_NAND_IO6_App*/
		GPIO_PIN_CFG(GPIOE, GPIO_PIN_10, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*73, PE10,		FMC_D7,			OFF,		SRAM_NAND_IO7_App*/
		GPIO_PIN_CFG(GPIOE, GPIO_PIN_11, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*74, PE11,		FMC_D8,			OFF,		SRAM_IO8_App*/
		GPIO_PIN_CFG(GPIOE, GPIO_PIN_12, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*75, PE12,		FMC_D9,			OFF,		SRAM_IO9_App*/
		GPIO_PIN_CFG(GPIOE, GPIO_PIN_13, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*76, PE13,		FMC_D10,		OFF,		SRAM_IO10_App*/
		GPIO_PIN_CFG(GPIOE, GPIO_PIN_14, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*77, PE14,		FMC_D11,		OFF,		SRAM_IO11_App*/
		GPIO_PIN_CFG(GPIOE, GPIO_PIN_15, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*78, PE15,		FMC_D12,		OFF,		SRAM_IO12_App*/
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_8, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*96, PD8,		FMC_D13,		OFF,		SRAM_IO13_App*/
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_9, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*97, PD9,		FMC_D14,		OFF,		SRAM_IO14_App*/
		GPIO_PIN_CFG(GPIOD, GPIO_PIN_10, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_12, GPIO_STATE_OFF),		/*98, PD10,		FMC_D15,		OFF,		SRAM_IO15_App*/
};

const gpio_pin_cfg_t gpio_nand_nwp_cfg[FMC_GPIO_NAND_NWP_COUNT] = {
		GPIO_PIN_CFG(GPIOF, GPIO_PIN_11, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_UP, GPIO_AF_0, GPIO_STATE_ON),		/*59, PF11,		GPIO_Output,	OFF,	NAND_nWP_App*/
};

void gpio_fmc_cfg_setup() {
	gpio_pins_cfg_setup(gpio_fmc_cfg, FMC_GPIO_COUNT);
	gpio_pins_cfg_setup(gpio_nand_nwp_cfg, FMC_GPIO_NAND_NWP_COUNT);
}


