/*
 * gpio_spi2_init.c
 *
 *  Created on: 20 июл. 2024 г.
 *      Author: ruslan
 */

#include "gpio_init.h"

#define SPI2_GPIO_COUNT 3

const gpio_pin_cfg_t gpio_spi2_cfg[SPI2_GPIO_COUNT] = {
		GPIO_PIN_CFG(GPIOI, GPIO_PIN_1, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_5, GPIO_STATE_OFF),		/*132, PI1,		SPI2_SCK,		OFF,		SCLKAIO_App*/
		GPIO_PIN_CFG(GPIOI, GPIO_PIN_2, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_5, GPIO_STATE_OFF),		/*133, PI2,		SPI2_MISO,		OFF,		MISOAIO_App*/
		GPIO_PIN_CFG(GPIOI, GPIO_PIN_3, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_5, GPIO_STATE_OFF),		/*134, PI3,		SPI2_MOSI,		OFF,		MOSIAIO_App*/
};

void gpio_spi2_cfg_setup() {
	gpio_pins_cfg_setup(gpio_spi2_cfg, SPI2_GPIO_COUNT);
}
