/*
 * gpio_ads866x_init.c
 *
 *  Created on: 10 июл. 2025 г.
 *      Author: Ruslan
 */

#include "gpio_init.h"

#define GPIO_ADS8665_COUNT 5

const gpio_pin_t GPI_RVS2_App = GPIO_PIN(GPIOB, GPIO_PIN_15);	/*95, PB15, GPIO_Input, RVS2_App*/
const gpio_pin_t GPO_ResetAI_App = GPIO_PIN(GPIOG, GPIO_PIN_6);	/*110, PG6, GPIO_Output, ResetAI_App*/
const gpio_pin_t GPI_RVS1_App = GPIO_PIN(GPIOA, GPIO_PIN_11);	/*122, PA11, GPIO_Input, RVS1_App*/
const gpio_pin_t GPO_CS1AI_App = GPIO_PIN(GPIOH, GPIO_PIN_14);	/*129, PH14, GPIO_Output, CS1AI_App*/
const gpio_pin_t GPO_CS2AI_App = GPIO_PIN(GPIOH, GPIO_PIN_15);	/*130, PH15, GPIO_Output, CS2AI_App*/

const gpio_pin_cfg_t gpio_ads8665_cfg[GPIO_ADS8665_COUNT] = {
		GPIO_PIN_CFG(GPIOB, GPIO_PIN_15, GPIO_MODE_IN, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_DOWN, GPIO_AF_0, GPIO_STATE_OFF),	/*95, PB15,		GPIO_Input,		OFF,		RVS2_App*/
		GPIO_PIN_CFG(GPIOG, GPIO_PIN_6, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0, GPIO_STATE_ON),		/*110, PG6,		GPIO_Output,	ON,		ResetAI_App*/
		GPIO_PIN_CFG(GPIOA, GPIO_PIN_11, GPIO_MODE_IN, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_DOWN, GPIO_AF_0, GPIO_STATE_OFF),	/*122, PA11,	GPIO_Input,		OFF,		RVS1_App*/
		GPIO_PIN_CFG(GPIOH, GPIO_PIN_14, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0, GPIO_STATE_ON),	/*129, PH14,	GPIO_Output,	ON,		CS1AI_App*/
		GPIO_PIN_CFG(GPIOH, GPIO_PIN_15, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0, GPIO_STATE_ON)		/*130, PH15,	GPIO_Output,	ON,		CS2AI_App*/
};


void gpio_ads8685_cfg_setup() {
	gpio_pins_cfg_setup(gpio_ads8665_cfg, GPIO_ADS8665_COUNT);
}
