#include "gpio_init.h"

void gpio_rcc_init() {
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOFEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOGEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOHEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOIEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOJEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOKEN;
}

//TODO: перенести инициализацию пинов в соответствующие модули
const gpio_pin_t GPO_Chr_Batt_App = GPIO_PIN(GPIOE, GPIO_PIN_3); /*2, PE3, GPIO_Output, Chr_Batt_App*/
const gpio_pin_t GPO_CS_PTC_App = GPIO_PIN(GPIOC, GPIO_PIN_13); /*8, PC13, GPIO_Output, CS_PTC_App*/
const gpio_pin_t GPI_Board_In1_App = GPIO_PIN(GPIOH, GPIO_PIN_3); /*44, PH3, GPIO_Input, Board_In1_App*/
const gpio_pin_t GPI_Board_In2_App = GPIO_PIN(GPIOH, GPIO_PIN_4); /*45, PH4, GPIO_Input, Board_In2_App*/
const gpio_pin_t GPI_BOOT1 = GPIO_PIN(GPIOB, GPIO_PIN_2); /*58, PB2/BOOT1, GPIO_Input, BOOT1*/
const gpio_pin_t GPO_NC = GPIO_PIN(GPIOA, GPIO_PIN_12); /*123, PA12, GPIO_Output, NC*/
const gpio_pin_t GPI_IO0_App_MC = GPIO_PIN(GPIOB, GPIO_PIN_4); /*162, PB4, GPIO_Input, IO0_App_MC*/
const gpio_pin_t GPI_IO1_App_MC = GPIO_PIN(GPIOB, GPIO_PIN_7); /*165, PB7, GPIO_Input, IO1_App_MC*/


//GPIO_PIN_CFG(GPIOE, GPIO_PIN_3, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0),					/*2, PE3,		GPIO_Output,	ON,		Chr_Batt_App*/
//GPIO_PIN_CFG(GPIOC, GPIO_PIN_13, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0, GPIO_STATE_ON),	/*8, PC13,		GPIO_Output,	ON,		CS_PTC_App*/
//GPIO_PIN_CFG(GPIOH, GPIO_PIN_3, GPIO_MODE_IN, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0),					/*44, PH3,		GPIO_Input,		OFF,		Board_In1_App*/
//GPIO_PIN_CFG(GPIOH, GPIO_PIN_4, GPIO_MODE_IN, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0),					/*45, PH4,		GPIO_Input,		OFF,		Board_In2_App*/
//GPIO_PIN_CFG(GPIOA, GPIO_PIN_3, , , , , GPIO_AF_ERR),																				/*47, PA3,		ADC1_IN3,		OFF,		Board_AI_App*/
//GPIO_PIN_CFG(GPIOA, GPIO_PIN_4, , , , , GPIO_AF_ERR),																				/*50, PA4,		DAC_OUT1,		OFF,		Board_AO_App*/
//GPIO_PIN_CFG(GPIOB, GPIO_PIN_0, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0),					/*56, PB0,		GPIO_Output,	OFF,	Board_Out3_App*/
//GPIO_PIN_CFG(GPIOB, GPIO_PIN_1, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0),					/*57, PB1,		GPIO_Output,	OFF,	Board_Out4_App*/
//GPIO_PIN_CFG(GPIOB, GPIO_PIN_2, GPIO_MODE_IN, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0),					/*58, PB2/BOOT1,GPIO_Input,		OFF,		BOOT1*/
//GPIO_PIN_CFG(GPIOB, GPIO_PIN_4, GPIO_MODE_IN, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0),					/*162, PB4,		GPIO_Input,		OFF,		IO0_App_MC*/
//GPIO_PIN_CFG(GPIOB, GPIO_PIN_7, GPIO_MODE_IN, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0),					/*165, PB7,		GPIO_Input,		OFF,		IO1_App_MC*/
