/*
 * gpio_dac7562_init.c
 *
 *  Created on: 23 дек. 2024 г.
 *      Author: ruslan
 */

#include "gpio_init.h"

#define GPIO_DAC7562_COUNT 6

const gpio_pin_t GPO_nCLR_App = GPIO_PIN(GPIOI, GPIO_PIN_11); /*13, PI11, GPIO_Output, nCLR_App*/
const gpio_pin_t GPO_OutDis_I_AO_App = GPIO_PIN(GPIOC, GPIO_PIN_2); /*34, PC2, GPIO_Output, OutDis_I_AO_App*/
const gpio_pin_t GPI_ErrorAO1_App = GPIO_PIN(GPIOG, GPIO_PIN_7); /*111, PG7, GPIO_Input, ErrorAO1_App*/
const gpio_pin_t GPI_ErrorAO2_App = GPIO_PIN(GPIOG, GPIO_PIN_8); /*112, PG8, GPIO_Input, ErrorAO2_App*/
const gpio_pin_t GPO_SYNCAO_App = GPIO_PIN(GPIOH, GPIO_PIN_13); /*128, PH13, GPIO_Output, SYNCAO_App*/
const gpio_pin_t GPO_nLDAC_App = GPIO_PIN(GPIOG, GPIO_PIN_10); /*153, PG10, GPIO_Output, nLDAC_App*/

const gpio_pin_cfg_t gpio_dac7562_cfg[GPIO_DAC7562_COUNT] = {
		GPIO_PIN_CFG(GPIOI, GPIO_PIN_11, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0, GPIO_STATE_ON),	/*13, PI11,		GPIO_Output,	OFF,	nCLR_App*/
		GPIO_PIN_CFG(GPIOC, GPIO_PIN_2, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0, GPIO_STATE_OFF),	/*34, PC2,		GPIO_Output,	OFF,	OutDis_I_AO_App*/
		GPIO_PIN_CFG(GPIOG, GPIO_PIN_7, GPIO_MODE_IN, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0, GPIO_STATE_OFF),		/*111, PG7,		GPIO_Input,		OFF,		ErrorAO1_App*/
		GPIO_PIN_CFG(GPIOG, GPIO_PIN_8, GPIO_MODE_IN, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0, GPIO_STATE_OFF),		/*112, PG8,		GPIO_Input,		OFF,		ErrorAO2_App*/
		GPIO_PIN_CFG(GPIOH, GPIO_PIN_13, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0, GPIO_STATE_ON),	/*128, PH13,	GPIO_Output,	ON,		SYNCAO_App*/
		GPIO_PIN_CFG(GPIOG, GPIO_PIN_10, GPIO_MODE_OUT, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_0, GPIO_STATE_ON),	/*153, PG10,	GPIO_Output,	OFF,	nLDAC_App*/
};

void gpio_dac7562_cfg_setup() {
	gpio_pins_cfg_setup(gpio_dac7562_cfg, GPIO_DAC7562_COUNT);
}

