/*
 * gpio_spi1_init.c
 *
 *  Created on: 25 мар. 2025 г.
 *      Author: ruslan
 */

#include "gpio_init.h"

#define SPI1_GPIO_COUNT 4

const gpio_pin_cfg_t gpio_spi1_cfg[SPI1_GPIO_COUNT] = {
		GPIO_PIN_CFG(GPIOA, GPIO_PIN_5, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_5, GPIO_STATE_OFF),		/*51, PA5,		SPI1_SCK,		OFF,		SPI_SCK_App_MC*/
		GPIO_PIN_CFG(GPIOA, GPIO_PIN_6, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_5, GPIO_STATE_OFF),		/*52, PA6,		SPI1_MISO,		OFF,		SPI_MISO_App_MC*/
		GPIO_PIN_CFG(GPIOA, GPIO_PIN_15, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_5, GPIO_STATE_ON),		/*138, PA15,	SPI1_NSS,		OFF,		SPI_CS_App_MC*/
		GPIO_PIN_CFG(GPIOB, GPIO_PIN_5, GPIO_MODE_AF, GPIO_OTYPE_PP, GPIO_OSPEED_VERY_HIGH, GPIO_PUPD_NONE, GPIO_AF_5, GPIO_STATE_OFF)		/*163, PB5,		SPI1_MOSI,		OFF,		SPI_MOSI_App_MC*/
};

void gpio_spi1_cfg_setup() {
	gpio_pins_cfg_setup(gpio_spi1_cfg, SPI1_GPIO_COUNT);
}
