/*
 * spi_ili9341_settings.c
 *
 *  Created on: 26 июн. 2025 г.
 *      Author: Ruslan
 */

#include "spi_settings.h"
#include "tft9341/tft9341.h"

const CFG_REG_SPI_TypeDef spi_ili9341_cfg = SPI_CFG(
		SPI_CPHA_FIRST,
		SPI_CPOL_IDLE_LOW,
		SPI_MSTR_MASTER,
		ILI9341_SPI_BR_FPCLK,
		SPI_LSBFIRST_MSB_FIRST,
		SPI_SSI_NSEL,
		SPI_SSM_ENA,
		SPI_RXONLY_DIS,
		SPI_DFF_8,
		SPI_CRCEN_DIS,
		SPI_BIDIOE_RX,
		SPI_BIDIMODE_UNIDIR,
		SPI_RXDMAEN_DIS,
		SPI_TXDMAEN_DIS,
		SPI_SSOE_DIS,
		SPI_FRF_MOTOROLA,
		SPI_ERRIE_DIS,
		GPO_CS_SPI5_App,
		10,
		10,
		30,
		TFT9341_DEFAULT_TRANSFER_ID);
